set search_path to public;

create extension if not exists pgcrypto;

create table if not exists roles (
  id bigint generated by default as identity primary key,
  name varchar(50) not null unique
);

create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(255) not null,
  phone varchar(30),
  password_hash varchar(255) not null,
  full_name varchar(255),
  status varchar(20) not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  deleted_at timestamptz
);

create table if not exists user_roles (
  role_id bigint not null,
  user_id bigint not null,
  primary key (role_id, user_id),
  constraint fk_user_roles_role foreign key (role_id) references roles(id),
  constraint fk_user_roles_user foreign key (user_id) references users(id)
);

create table if not exists guards (
  base_salary numeric(38,2) not null,
  hire_date date,
  overtime_rate numeric(38,2) not null,
  per_day_rate numeric(38,2) not null,
  created_at timestamptz not null,
  deleted_at timestamptz,
  id bigint generated by default as identity primary key,
  supervisor_user_id bigint,
  updated_at timestamptz not null,
  user_id bigint not null unique,
  status varchar(20) not null,
  phone varchar(30),
  employee_code varchar(50) not null unique,
  first_name varchar(100) not null,
  last_name varchar(100),
  constraint fk_guards_user foreign key (user_id) references users(id),
  constraint fk_guards_supervisor_user foreign key (supervisor_user_id) references users(id)
);

create index if not exists idx_user_roles_role_id on user_roles (role_id);
create index if not exists idx_user_roles_user_id on user_roles (user_id);
create index if not exists idx_guards_supervisor_user_id on guards (supervisor_user_id);

insert into roles (name)
values ('ADMIN'), ('SUPERVISOR'), ('GUARD'), ('CLIENT')
on conflict (name) do nothing;

insert into users (email, phone, password_hash, full_name, status, created_at, updated_at, deleted_at)
values (
  'admin@zplusesecurity.com',
  null,
  crypt('admin123', gen_salt('bf')),
  'Admin',
  'ACTIVE',
  now(),
  now(),
  null
)
on conflict do nothing;

insert into user_roles (role_id, user_id)
select r.id, u.id
from roles r
join users u on u.email = 'admin@zplusesecurity.com'
where r.name = 'ADMIN'
on conflict do nothing;
